package com.zhihui.bishe.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import javax.sql.DataSource;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
 

@RestController
@RequestMapping("/api/admin")
public class AdminController {

    @Autowired
    private DataSource dataSource;

    @PostMapping("/import-sql")
    public String importSql(@RequestParam(required = false) String path) {
        String[] candidates = new String[] {
                path,
                "smart--traffic.sql",
                "./smart--traffic.sql",
                "D:/biyesheji/bishe/smart--traffic.sql"
        };

        File sqlFile = null;
        for (String p : candidates) {
            if (p == null) continue;
            File f = new File(p);
            if (f.exists() && f.isFile()) {
                sqlFile = f;
                break;
            }
        }
        if (sqlFile == null) {
            return "SQL file not found. Tried defaults.";
        }

        try (Connection conn = dataSource.getConnection();
             Statement stmt = conn.createStatement();
             BufferedReader reader = new BufferedReader(new FileReader(sqlFile))) {

            StringBuilder sb = new StringBuilder();
            String line;
            int executed = 0;
            while ((line = reader.readLine()) != null) {
                // skip comments
                String trimmed = line.trim();
                if (trimmed.startsWith("--") || trimmed.startsWith("/*") || trimmed.startsWith("SET ")) {
                    continue;
                }
                sb.append(line).append("\n");
                if (trimmed.endsWith(";")) {
                    String sql = sb.toString();
                    sql = sql.replaceAll("\r\n", "\n");
                    sql = sql.trim();
                    if (sql.endsWith(";")) {
                        sql = sql.substring(0, sql.length()-1);
                    }
                    if (!sql.isEmpty()) {
                        try {
                            stmt.execute(sql);
                        } catch (Exception ex) {
                            // continue on error but log
                            System.out.println("Import stmt failed: " + ex.getMessage());
                        }
                        executed++;
                    }
                    sb.setLength(0);
                }
            }

            // return count in table
            try (ResultSet rs = stmt.executeQuery("SELECT COUNT(*) FROM traffic_violation")) {
                if (rs.next()) {
                    int cnt = rs.getInt(1);
                    return "Imported statements: " + executed + "; traffic_violation rows: " + cnt;
                }
            }
            return "Imported statements: " + executed;
        } catch (Exception e) {
            e.printStackTrace();
            return "Import failed: " + e.getMessage();
        }
    }

    @GetMapping(value = "/export-violations", produces = "text/plain;charset=UTF-8")
    public String exportViolations() {
        StringBuilder out = new StringBuilder();
        out.append("-- Export of traffic_violation\n");
        out.append("-- Generated by AdminController\n\n");
        try (Connection conn = dataSource.getConnection();
             Statement stmt = conn.createStatement();
             ResultSet rs = stmt.executeQuery("SELECT * FROM traffic_violation")) {

            java.sql.ResultSetMetaData md = rs.getMetaData();
            int cols = md.getColumnCount();

            while (rs.next()) {
                StringBuilder colsPart = new StringBuilder();
                StringBuilder valsPart = new StringBuilder();
                colsPart.append("(");
                valsPart.append("(");
                for (int i = 1; i <= cols; i++) {
                    String col = md.getColumnName(i);
                    Object val = rs.getObject(i);
                    colsPart.append("`").append(col).append("`");
                    if (val == null) {
                        valsPart.append("NULL");
                    } else if (val instanceof Number) {
                        valsPart.append(val.toString());
                    } else {
                        String s = val.toString().replace("'", "''");
                        valsPart.append("'").append(s).append("'");
                    }
                    if (i < cols) {
                        colsPart.append(", ");
                        valsPart.append(", ");
                    }
                }
                colsPart.append(")");
                valsPart.append(")");
                out.append("INSERT INTO `traffic_violation` ").append(colsPart).append(" VALUES ").append(valsPart).append(";\n");
            }
            return out.toString();
        } catch (Exception e) {
            e.printStackTrace();
            return "Export failed: " + e.getMessage();
        }
    }
}


